# Generated by Django 3.1.3 on 2020-12-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posr',
            new_name='Post',
        ),
    ]
