# Generated by Django 3.1.3 on 2020-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=300)),
                ('desc', models.CharField(default='', max_length=4000)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
